/**
 * Golden-fixture tests for averageWs and averageAttackRound.
 *
 * Fixture values were generated by wsdist_beta/test_harness.py — the Python
 * reference implementation.  Re-run the harness whenever you change the
 * fixtures intentionally, but a failing test means a regression.
 */
import { describe, it, expect } from 'vitest'
import { buildPlayer, buildEnemy } from '../createPlayer'
import { averageWs, averageAttackRound } from '../actions'
import type { Gearset, GearItem } from '@/types/gear'
import golden from './fixtures/sam_war_gekkei_tachi_fudo.json'

// ---------------------------------------------------------------------------
// Shared gear
// ---------------------------------------------------------------------------

const EMPTY: GearItem = {
  Name: 'Empty',
  Name2: 'Empty',
  'Skill Type': 'None',
  Type: 'None',
  Jobs: ['war','mnk','whm','blm','rdm','thf','pld','drk','bst','brd','rng',
         'smn','sam','nin','drg','blu','cor','pup','dnc','sch','geo','run'],
}

const GEKKEI_R0: GearItem = {
  Name: 'Gekkei',
  Name2: 'Gekkei R0',
  Rank: 0,
  Type: 'Weapon',
  'Skill Type': 'Great Katana',
  STR: 15,
  DEX: 15,
  DMG: 300,
  Delay: 450,
  Accuracy: 40,
  Attack: 30,
  'Magic Accuracy': 40,
  'Great Katana Skill': 255,
  'Magic Accuracy Skill': 242,
  DA: 10,
  Jobs: ['sam'],
}

function emptyGearset(main: GearItem = EMPTY): Gearset {
  return {
    main, sub: EMPTY, ranged: EMPTY, ammo: EMPTY,
    head: EMPTY, neck: EMPTY, ear1: EMPTY, ear2: EMPTY,
    body: EMPTY, hands: EMPTY, ring1: EMPTY, ring2: EMPTY,
    back: EMPTY, waist: EMPTY, legs: EMPTY, feet: EMPTY,
  }
}

// ---------------------------------------------------------------------------
// Player & enemy matching the harness
// ---------------------------------------------------------------------------

const player = buildPlayer('sam', 'war', 0, emptyGearset(GEKKEI_R0), {}, {})
const enemy  = buildEnemy(golden.enemy as Record<string, unknown>)

// ---------------------------------------------------------------------------
// averageWs — Tachi: Fudo vs Apex Bats
// ---------------------------------------------------------------------------

describe('averageWs — Tachi: Fudo, SAM/WAR ML0, Gekkei R0, vs Apex Bats', () => {
  it('damage at 1000 TP matches Python', () => {
    const result = averageWs(player, enemy, 'Tachi: Fudo', 1000, 'melee', false)
    expect(result.damage).toBeCloseTo(golden.results.averageWs['1000tp'].damage, 0)
  })

  it('damage at 2000 TP matches Python', () => {
    const result = averageWs(player, enemy, 'Tachi: Fudo', 2000, 'melee', false)
    expect(result.damage).toBeCloseTo(golden.results.averageWs['2000tp'].damage, 0)
  })

  it('damage at 3000 TP matches Python', () => {
    const result = averageWs(player, enemy, 'Tachi: Fudo', 3000, 'melee', false)
    expect(result.damage).toBeCloseTo(golden.results.averageWs['3000tp'].damage, 0)
  })
})

// ---------------------------------------------------------------------------
// averageAttackRound — TP phase
// ---------------------------------------------------------------------------

describe('averageAttackRound — SAM/WAR ML0, Gekkei R0, vs Apex Bats', () => {
  it('physical damage per round matches Python', () => {
    const result = averageAttackRound(player, enemy, 0, 1000, false)
    expect(result.physicalDamage).toBeCloseTo(golden.results.averageAttackRound.physicalDamage, 0)
  })

  it('time-to-WS matches Python (tpReturn = timePerWs in non-simulation path)', () => {
    const result = averageAttackRound(player, enemy, 0, 1000, false)
    // In the non-simulation path, tpReturn holds timePerWs (seconds from startingTp to wsThreshold)
    expect(result.tpReturn).toBeCloseTo(golden.results.averageAttackRound.timePerWs, 0)
  })
})
